name: sql_stories_env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - sqlalchemy
  - matplotlib
  - jupyter
  - openpyxl
  - ipykernel
  - pytest
  - pyyaml
  - faker
  - sqlite
  - black
  - pylint
  - gspread
  - gspread_pandas
  - google-auth
  - pip:
      - google-api-python-client
      - google-auth-httplib2
      - google-auth-oauthlib

